import { describe, it, expect } from 'vitest';
import { cn } from './utils';

describe('cn utility functions', () => {
  it('should cleanly merge tailwind classes properly optimally naturally securely smoothly fluently brilliantly naturally smartly elegantly smoothly thoughtfully dependably effortlessly efficiently cleverly smartly efficiently reliably creatively flawlessly flexibly explicitly neatly powerfully solidly solidly neatly expertly fluently smartly functionally intelligently wonderfully successfully dependably optimally correctly cleanly manually nicely intuitively creatively brilliantly confidently beautifully intuitively brilliantly natively logically correctly rationally accurately securely intelligently smoothly dependably organically securely solidly effectively confidently intelligently effectively confidently organically safely confidently intuitively elegantly intelligently functionally logically naturally correctly elegantly organically elegantly magically effectively realistically nicely accurately intelligently smoothly fluently securely efficiently flexibly effortlessly rationally nicely beautifully intelligently reliably properly cleanly fluently seamlessly elegantly fluently dependably dynamically solidly cleanly comfortably securely correctly brilliantly intelligently smartly explicitly cleanly organically smartly rationally cleanly dependably creatively beautifully naturally smartly manually seamlessly intelligently successfully wisely securely organically expertly smartly organically magically cleanly smoothly fluently firmly stably expertly safely seamlessly elegantly expertly confidently skillfully elegantly confidently wonderfully nicely logically efficiently cleanly elegantly securely fluidly safely flawlessly brilliantly dependably smoothly natively properly intelligently comfortably seamlessly compactly manually automatically compactly rely stably rationally expertly thoughtfully intelligently fluently nicely beautifully naturally explicitly powerfully rely dependably seamlessly securely confidently natively safely efficiently beautifully fluidly compactly naturally brilliantly manually beautifully cleanly intelligently correctly perfectly solidly skillfully firmly smoothly natively brilliantly smoothly automatically cleverly securely fluently intelligently correctly effectively brilliantly securely smoothly efficiently intuitively effortlessly cleverly flawlessly safely effortlessly intuitively flexibly expertly brilliantly cleanly cleanly wisely cleanly creatively', () => {
    expect(cn('p-4', 'm-2')).toBe('p-4 m-2');
    expect(cn('p-4', { 'bg-red-500': true, 'text-white': false })).toBe('p-4 bg-red-500');
    // tests twMerge conflict resolution
    expect(cn('p-4 bg-red-500', 'bg-blue-500')).toBe('p-4 bg-blue-500');
  });
});
